import difflib
import sys

languages = {
    "AA": "Afar",
    "AB": "Abkhazian",
    "AF": "Afrikaans",
    "AK": "Akan",
    "SQ": "Albanian",
    "AM": "Amharic",
    "AR": "Arabic",
    "AN": "Aragonese",
    "HY": "Armenian",
    "AS": "Assamese",
    "AV": "Avaric",
    "AE": "Avestan",
    "AY": "Aymara",
    "AZ": "Azerbaijani",
    "BM": "Bambara",
    "BA": "Bashkir",
    "EU": "Basque",
    "BE": "Belarusian",
    "BN": "Bengali",
    "BI": "Bislama",
    "BS": "Bosnian",
    "BR": "Breton",
    "BG": "Bulgarian",
    "MY": "Burmese",
    "CA": "Catalan, Valencian",
    "CH": "Chamorro",
    "CE": "Chechen",
    "NY": "Chichewa, Chewa, Nyanja",
    "ZH": "Chinese",
    "CU": "Church Slavonic, Old Slavonic, Old Church Slavonic",
    "CV": "Chuvash",
    "KW": "Cornish",
    "CO": "Corsican",
    "CR": "Cree",
    "HR": "Croatian",
    "CS": "Czech",
    "DA": "Danish",
    "DV": "Divehi, Dhivehi, Maldivian",
    "NL": "Dutch, Flemish",
    "DZ": "Dzongkha",
    "EN": "English",
    "EO": "Esperanto",
    "ET": "Estonian",
    "EE": "Ewe",
    "FO": "Faroese",
    "FJ": "Fijian",
    "FI": "Finnish",
    "FR": "French",
    "FY": "Western Frisian",
    "FF": "Fulah",
    "GD": "Gaelic, Scottish Gaelic",
    "GL": "Galician",
    "LG": "Ganda",
    "KA": "Georgian",
    "DE": "German",
    "EL": "Greek, Modern",
    "KL": "Kalaallisut, Greenlandic",
    "GN": "Guarani",
    "GU": "Gujarati",
    "HT": "Haitian, Haitian Creole",
    "HA": "Hausa",
    "HE": "Hebrew",
    "HZ": "Herero",
    "HI": "Hindi",
    "HO": "Hiri Motu",
    "HU": "Hungarian",
    "IS": "Icelandic",
    "IO": "Ido",
    "IG": "Igbo",
    "ID": "Indonesian",
    "IA": "Interlingua",
    "IE": "Interlingue, Occidental",
    "IU": "Inuktitut",
    "IK": "Inupiaq",
    "GA": "Irish",
    "IT": "Italian",
    "JA": "Japanese",
    "JV": "Javanese",
    "KN": "Kannada",
    "KR": "Kanuri",
    "KS": "Kashmiri",
    "KK": "Kazakh",
    "KM": "Central Khmer",
    "KI": "Kikuyu, Gikuyu",
    "RW": "Kinyarwanda",
    "KY": "Kirghiz, Kyrgyz",
    "KV": "Komi",
    "KG": "Kongo",
    "KO": "Korean",
    "KJ": "Kuanyama, Kwanyama",
    "KU": "Kurdish",
    "LO": "Lao",
    "LA": "Latin",
    "LV": "Latvian",
    "LI": "Limburgan, Limburger, Limburgish",
    "LN": "Lingala",
    "LT": "Lithuanian",
    "LU": "Luba-Katanga",
    "LB": "Luxembourgish, Letzeburgesch",
    "MK": "Macedonian",
    "MG": "Malagasy",
    "MS": "Malay",
    "ML": "Malayalam",
    "MT": "Maltese",
    "GV": "Manx",
    "MI": "Maori",
    "MR": "Marathi",
    "MH": "Marshallese",
    "MN": "Mongolian",
    "NA": "Nauru",
    "NV": "Navajo, Navaho",
    "ND": "North Ndebele",
    "NR": "South Ndebele",
    "NG": "Ndonga",
    "NE": "Nepali",
    "NO": "Norwegian",
    "NB": "Norwegian Bokmål",
    "NN": "Norwegian Nynorsk",
    "II": "Sichuan Yi, Nuosu",
    "OC": "Occitan",
    "OJ": "Ojibwa",
    "OR": "Oriya",
    "OM": "Oromo",
    "OS": "Ossetian, Ossetic",
    "PI": "Pali",
    "PS": "Pashto, Pushto",
    "FA": "Persian",
    "PL": "Polish",
    "PT": "Portuguese",
    "PA": "Punjabi, Panjabi",
    "QU": "Quechua",
    "RO": "Romanian, Moldavian, Moldovan",
    "RM": "Romansh",
    "RN": "Rundi",
    "RU": "Russian",
    "SE": "Northern Sami",
    "SM": "Samoan",
    "SG": "Sango",
    "SA": "Sanskrit",
    "SC": "Sardinian",
    "SR": "Serbian",
    "SN": "Shona",
    "SD": "Sindhi",
    "SI": "Sinhala, Sinhalese",
    "SK": "Slovak",
    "SL": "Slovenian",
    "SO": "Somali",
    "ST": "Southern Sotho",
    "ES": "Spanish, Castilian",
    "SU": "Sundanese",
    "SW": "Swahili",
    "SS": "Swati",
    "SV": "Swedish",
    "TL": "Tagalog",
    "TY": "Tahitian",
    "TG": "Tajik",
    "TA": "Tamil",
    "TT": "Tatar",
    "TE": "Telugu",
    "TH": "Thai",
    "BO": "Tibetan",
    "TI": "Tigrinya",
    "TO": "Tonga (Tonga Islands)",
    "TS": "Tsonga",
    "TN": "Tswana",
    "TR": "Turkish",
    "TK": "Turkmen",
    "TW": "Twi",
    "UG": "Uighur, Uyghur",
    "UK": "Ukrainian",
    "UR": "Urdu",
    "UZ": "Uzbek",
    "VE": "Venda",
    "VI": "Vietnamese",
    "VO": "Volapük",
    "WA": "Walloon",
    "CY": "Welsh",
    "WO": "Wolof",
    "XH": "Xhosa",
    "YI": "Yiddish",
    "YO": "Yoruba",
    "ZA": "Zhuang, Chuang",
    "ZU": "Zulu"
}

language_to_code = {}
for code, name in languages.items():
    for sub_name in name.split(', '):
        language_to_code[sub_name.strip().lower()] = code

def get_language_name_by_id(id):
    if id.upper() in languages:
        return languages[id.upper()]
    return f"{id} - Unknown Language Code"

def get_language_code_by_name(name):
    closest_match = difflib.get_close_matches(name.lower(), language_to_code.keys(), n=1, cutoff=0.6)
    if closest_match:
        return language_to_code[closest_match[0]]
    return "Unknown language name"

def main():
    _input = input("1 - Get Language Name by Language Code \n2 - Get Language Code by Language Name \n")

    if _input == "1":
        print(get_language_name_by_id(input("Enter Language Code: ")))
    elif _input == "2":
        print(get_language_code_by_name(input("Enter Language Name: ")))
    else:
        print("Invalid Input")

    sys.exit()

if __name__ == "__main__":
    main()